### PR TITLE
refactor(modularize-imports): Move code

### PR DESCRIPTION
**Pull request by kdy1**
We are planning to move code to this repository to make maintenance easier.
But the license is a bit different - swc plugins are licensed under Apache 2.0 and have CLA (although I don't care about it.. I configured it just to avoid process like this)

So I'm asking the external contributors if they agree with moving the code.

Please leave a comment with `I agree` if you agree with these changes

---

cc

 - [x] @losfair for https://github.com/vercel/next.js/commit/860c97ccf597eddec9422cab06ab8a7cc328d8bb
 - [x] @nnnnoel for https://github.com/vercel/next.js/commit/40f0eb126ba08dd821f8e7ce95dc61bd1eac2fc0

### CODE REVIEW

**Comment by nnnnoel** [comment]
I agree.

**Comment by kdy1** [comment]
Thanks!

**Comment by losfair** [comment]
I agree

**Comment by kdy1** [comment]
Thanks!

**Pull request merged**
