### PR TITLE
build(cargo): bump up swc_core

### PR DESCRIPTION
**Pull request by kwonoj**
Supersede #123 + for the WEB-307.

#123 worked, but there seems some manual update required (for the test fixtures). Bump is needed anyway so took manual update.

### CODE REVIEW

**Review by kdy1 — CHANGES_REQUESTED** [review]
Please use `./scripts/update-bump-all.sh` instead

**Comment by kwonoj** [comment]
Script seems not universally workable, on local seeing

```
❯ ./scripts/update-bump-all.sh
error: Found argument '--workspace' which wasn't expected, or isn't valid in this context
```

**Comment by kwonoj** [comment]
Tried to amend by removing `--workspace` and getting this instead:

```
    Checking swc_tailwind's dependencies
Error: dependencies swc_atoms, swc_ecmascript, swc_ecma_transforms_testing, swc_plugin don't exist
````

Any suggestions to make script work? @kdy1

**Comment by kdy1** [comment]
It's a universal script

**Comment by kdy1** [comment]
The problem is the version of your `cargo` or `cargo-edit`

**Comment by kwonoj** [comment]
I'm using latest for cargo-edit.

Just checking, looks like --workspace is deprecated with latest: https://github.com/killercup/cargo-edit/issues/827

**Pull request closed without merging**
