### PR TITLE
feat(styled-components): Implement minification

### LINKED ISSUE #143: styled-components minify doesn't work with provided target
Hey, I was trying out `@swc/plugin-styled-components`, but compiled output with selected target `es2020` doesn't remove comments and white spaces. Here is [repo](https://github.com/huv1k/swc-styled-components-target) with reproduction. 

For input, I used [input](https://github.com/swc-project/plugins/blob/main/packages/styled-components/transform/tests/fixtures/.minify-css-to-use-without-transpilation/code.js) from tests and output is like [this](https://github.com/huv1k/swc-styled-components-target/blob/master/out.js). Comments are still presented and output inside template literals is not minified. 

## How to reproduce
1. Clone repro
2. `yarn install`
3. `yarn run compile`

### PR DESCRIPTION
**Pull request by ciffelia**
This implements `minify` option in styled-components plugin. The minification algorithm and unit tests are ported from `babel-plugin-styled-components`.

Note that CSS code in helper functions (`keyframes`, `css`, etc.) are currently not always processed. I think there is a bug in `is_helper` function, so I'll fix it in another pull request later.

fixes #143
cf. vercel/next.js#30802

### CODE REVIEW

**Review by kdy1 — CHANGES_REQUESTED** [review]
I think we should use `swc_css` or `lightningcss` for minification.

(I prefer `lightningcss`, because turbopack is going to use it)

**Comment by ciffelia** [comment]
> I think we should use `swc_css` or `lightningcss` for minification.
> 
> (I prefer `lightningcss`, because turbopack is going to use it)

Lightningcss does not support line comments. swc_css supports line comments, but I doubt it works for all syntax styled-components supports. For example, swc_css might not be able to parse the following style into AST.

```js
const Box = styled.div`
  animation: ${p => p.anim};
  ${p => p.type}: red;
  ${p => p.additionalRules};

  ${MyComponent} {
    color: red;
  }
`

// <Box animation="slidein 3s linear 1s" type="background-color" additionalRules="opacity: 0.1">foo</Box>
```

So I think using lightningcss or swc_css would cause regression against the regex-based method used in babel-plugin-styled-components.

**Review by kdy1 — APPROVED** [review]

**Comment by phiter** [comment]
Do you know what might be needed to make minification work with the `css` helper? You mentioned it doesn't currently work and I tried it and only `styled.*` components get minified.

**Comment by phiter** [comment]
Ah I just saw your other PR, looking forward to using that! Thank you.

**Pull request merged**
