### PR TITLE
refactor(emotion): Move code

### PR DESCRIPTION
**Pull request by kdy1**
We are planning to move code to this repository to make maintenance easier.
But the license is a bit different - swc plugins are licensed under Apache 2.0 and have CLA (although I don't care about it.. I configured it just to avoid process like this)

So I'm asking the external contributors if they agree with moving the code.

Please leave a comment with `I agree` if you agree with these changes

---

cc

 - [x] @JohnDaly for https://github.com/vercel/next.js/commit/24c0fc0169ccc009e75d7099c262e9cf075a38ca
 - [x] @magic-akari for https://github.com/vercel/next.js/commit/78aefee1c643ed43001b6dbacca73a2bf22aca2a

### CODE REVIEW

**Comment by JohnDaly** [comment]
I agree

**Comment by kdy1** [comment]
Thanks!

**Comment by magic-akari** [comment]
I agree

**Comment by kdy1** [comment]
Thanks!

**Pull request merged**
